services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: skilltrack
      POSTGRES_PASSWORD: skilltrack
      POSTGRES_DB: skilltrack_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # === Database ===
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/skilltrack_db
      SPRING_DATASOURCE_USERNAME: skilltrack
      SPRING_DATASOURCE_PASSWORD: skilltrack

      # === Mailtrap (dev only) ===
      SPRING_MAIL_HOST: smtp.mailtrap.io
      SPRING_MAIL_PORT: 2525
      SPRING_MAIL_USERNAME: 303e212c2008d8
      SPRING_MAIL_PASSWORD: 449e25e057bfc3
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_DEFAULT_ENCODING: UTF-8
      SPRING_MAIL_FROM: "SkillTrack <no-reply@skilltrack.app>"

      # === JWT ===
      JWT_SECRET: ma_super_cle_ultra_secrete
      JWT_EXPIRATION: 604800000

      # === Application ===
      SPRING_APPLICATION_NAME: skilltrack-backend
      SERVER_PORT: 8080
      APP_BASE_URL: http://localhost:8080

    ports:
      - "8080:8080"
    # Optionnel : permet dâ€™attendre que la DB soit disponible
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U skilltrack"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8080
    ports:
      - "3000:3000"

volumes:
  pgdata:
